---
- name: Validate role vars
  assert:
    that:
      - verbosity is not defined or verbosity in ("debug","trace")
      - install_timeout_seconds is not defined or install_timeout_seconds is integer
    quiet: true

- name: Validate targets
  assert:
    that:
      - target_name_map[item] is defined
    quiet: true
  loop: "{{ targets }}"
