---
- name: Targets is set
  ansible.builtin.assert:
    that: targets is defined
    fail_msg: "'targets' must be set"

- name: Check targets is empty
  ansible.builtin.set_fact:
    no_targets: "{{ true if not targets }}"
  when: targets is defined

- name: Targets contains at least one installation target
  ansible.builtin.assert:
    that: no_targets != true
    fail_msg: "Targets must contain at least one installation target"

- name: Check ansible_env for required environment variables
  ansible.builtin.set_fact:
    account_id_is_set: "{{ ansible_env.NEW_RELIC_ACCOUNT_ID is defined }}"
    api_key_is_set: "{{ ansible_env.NEW_RELIC_API_KEY is defined }}"

- name: Check environment for required environment variables
  when: not (account_id_is_set and api_key_is_set)
  loop: "{{ environment }}"
  ansible.builtin.set_fact:
    account_id_is_set: "{{ item.NEW_RELIC_ACCOUNT_ID is defined }}"
    api_key_is_set: "{{ item.NEW_RELIC_API_KEY is defined }}"
  until: account_id_is_set and api_key_is_set
  retries: 0
  no_log: true

- name: Assert NEW_RELIC_ACCOUNT_ID is set
  ansible.builtin.assert:
    that: account_id_is_set
    msg: NEW_RELIC_ACCOUNT_ID is required and was not found. Please set this as an environment variable in your play under `environment`

- name: Assert NEW_RELIC_API_KEY is set
  ansible.builtin.assert:
    that: api_key_is_set
    msg: NEW_RELIC_API_KEY is required and was not found. Please set this as an environment variable in your play under `environment`

- name: Validate role vars
  ansible.builtin.assert:
    that:
      - verbosity is not defined or verbosity in ("debug","trace")
      - install_timeout_seconds is not defined or install_timeout_seconds is integer
    quiet: true

- name: Validate targets
  ansible.builtin.assert:
    that:
      - target_name_map[item] is defined
    quiet: true
  loop: "{{ targets }}"
